### ISSUE TITLE
Car updates from sensors

### ISSUE THREAD

**Issue by nikalc** [DIT112-V21/group-09#37]
As a user I want the results reported back from the car sensors to be accurate so that I get correct updates.

Acceptance Criteria:
Scenario: The user receives automated reports from the car sensors and the information is saved in time order

Given that the user receives reports from the car sensors
When the user views the results
Then the automated updates are shown in time order.

**Comment by kam56** [comment]
I do not remember what we exactly meant by accurate. Can someone clarify it a bit?

**Comment by axe007** [comment]
It is not regarding accuracy of the sensors, like UltraSonic is accurate down to +-0.1millimeter or something. We just take what's programmed in SMCE.

On our case, I would take "accurate" as more like up-to-date if MQTT communication is 2-3 seconds late. If latest data is 3 seconds late, it is not "accurate" since car already travelled bit more and maybe hitting something already. And if measurement is just within 0.5 seconds, then it could be acceptable since it is still "fairly" new data.

**Comment by kam56** [comment]
right. 
Thank you, Altan.
